language: node_js
node_js:
  - "4.0"
  - "4.1"
  - "4.2"
  - "5.3"

sudo: required

before_install:
  chmod +x ./travis_before_install.sh
  sudo ./travis_before_install.sh

after_success:
  npm run coveralls